### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by YarikZubyk** [YarikZubyk/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by zubyktest** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by zubyktest** [comment]
Hi my name is Yaroslav. I like web development.<br> I like
                                technologies such as HTML CSS PHP OOP MySQL.<br> I am currently developing websites on
                                WordPress
                                <br>1.3
                                years of experience.<br>In the future I want to become a php dev.

**Comment by YarikZubyk** [comment]
Thanx for update
