### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by YarikZubyk** [YarikZubyk/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by zubyktest** [comment]
LIFE & EDUCATION
To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.

LANGUAGES
🇺🇸 ENGLISH 🇨🇳 MANDARIN 🇯🇵 JAPANESE

SKILLS
KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

CHARACTER
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

LIFE LESSON
You must defeat Sheng Long to stand a chance.

LIKES 😃
GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

DISLIKES 😞
BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

WANTS 🥺
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by YarikZubyk** [comment]
Дякую!

**Comment by zubyktest** [comment]
<div class="second-middle-conteiner">
                        <div class="other-info-cantainer">
                            <section>
                            <h3>Languages</h3>
                            <p class="tags small">
                                <a hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6;
                                    <span>УКРАЇНСЬКА</span></a> <a lang="ru" rel="alternate" class="language"
                                                                   lang="ru">&#x1f1f7;&#x1f1fa;
                                <span>РУССКИЙ</span></a> <span class="language"
                                                               lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                        </section>
                            <section>
                                <h3>SKILLS</h3>
                                <p class="tags small">
                                    HTML CSS OOP PHP WORDPRESS MICROSOFT OFFICE PHOTOSHOP WINDOWS
                                </p>
                            </section>
                            <section>
                                <h3>CHARACTER</h3>
                                <p class="tags small">
                                    GOOD BOY SMILE DANCE
                                </p>
                            </section>
                            <section>
                                <h3>LIKES&#x1f603;</h3>
                                <p class="tags small">
                                    MUSIC GIRL SPORT VOLLEYBALL FOOTBALL PC GAMES SMILE SHUTKI COMPANY TEAM MANCHESTER UNITED MOVIE FILMS MARVEL AVENGERS CODDING DOGS CAT
                                </p>
                            </section>
                            <section>
                                <h3>DISLIKES&#x1f61e;</h3>
                                <p class="tags small">
                                    SMOKE RACISM BAD PEOPLE ROCK EGO
                                </p>
                            </section>
                            <section>
                                <h3>WANTS&#x1f97a;</h3>
                                <p class="tags small">
                                    END OF QUARANTINE TRAVEL TOMORROWLAND STUDY PHP VISIT USA FRANCE ITALY GERMANY etc.
                                </p>
                            </section>
                        </div>
                    </div>

**Comment by YarikZubyk** [comment]
finish line!!!!!!
